//@version=4
study("Crypto - Price Action Bars", overlay=true)
//, max_labels_count=100

sdj                   = input(true, title="Show Doji?")
// spb                   = input(true, title="Show Pinbar?")
stz                   = input(true, title="Show Tweezer Top/Bottom?")
skgr                  = input(true, title="Show Kangaroo Tail?")
sfk                   = input(true, title="Show Fakey. Inside bar false-break?")
senf                  = input(true, title="Show Engulfing. V-Shaped Reversal?")
sms                   = input(true, title="Show Morning/Evening Star?")
srft                  = input(true, title="Show Rising/Failing Three?")
siz                   = input(true, title="Show Indecision Zone Break out?")
sbt                   = input(true, title="Show Broadening Triangle?")
sstr                  = input(true, title="Show Symmetrical Triangle?")
sss                   = input(true, title="Show Stair Step?")
sib                   = input(true, title="Show Coiling Inside bars Break out?")
scz                   = input(true, title="Show Congestion Zone?")
s3br                  = input(true, title="Show Three Bar Reversal?")
spi                   = input(true, title="Show Pressure Increase?")
spz                   = input(true, title="Show Pressure Zone?")
s3ws                  = input(true, title="Show Three White Soldiers/Black Crows bars?")
ssp                   = input(true, title="Show Stalled/Advance Block pattern?")
std                   = input(true, title="Show The Deceleration?")
sac                   = input(true, title="Show The Anti-Climax?")
eav                   = input(8, minval=1, maxval=100, title="EMA Depth For Body Average/Volatility")
wav                   = input(13, minval=1, maxval=100, title="EMA Depth For Wick Average/Volatility")
pivotlbar             = input(8, minval=1, maxval=99, title="Length to Highest/Lowest")
wm                    = input(defval = 2.0, step = 0.5, minval = 2.0, maxval=5.0, title="Wick Multiplier")
bodyPercentage        = input(defval = 0.40, step = 0.1, minval = 0.1, maxval=0.99, title="Body Percentage")
pctShadow             = input(50, minval=1, maxval=99, title="Percentage Input Of Up/Down Shadow, What % The Wick Of Candle Has To Be Compared To Body")
color_be_momentum     = input(color.maroon, "Color Bearish Momentum")
color_bu_momentum     = input(color.lime, "Color Bullish Momentum")
color_reverse         = input(color.purple, "Color Reverse")
// color_pinbar          = input(color.silver, "Color Pinbar")
color_breakout        = input(color.yellow, "Color Break out")
color_falsebreak      = input(color.orange, "Color False Break")

//EMA
ema25 = ema(close, 25)
closeAboveEMA25 = low > ema25 
closeBelowEMA25 = high < ema25 

// spread|range
spread    = abs(close - open)
// spread    = bodyHigh - bodyLow
bodyHigh  = max(close, open)
bodyLow   = min(close, open)
range     = high - low
upShadow  = high - bodyHigh
dnShadow  = bodyLow - low
whiteBody = open < close
blackBody = open > close

// EMA
spreadAvg             = ema(spread, eav)
rangeAvg              = ema(range, eav)
averageTopWickSize    = sma(upShadow, wav)
averageBottomWickSize = sma(dnShadow, wav)

bigBody         = spread > spreadAvg*2
mediumLongBody  = spread > spreadAvg and spread < spreadAvg*2
longBody        = spread > spreadAvg
smallBody       = spread < spreadAvg
mediumSmallBody = spread < spreadAvg and spread > spreadAvg/2
tinyBody        = spread < spreadAvg/2
bodyMiddle      = spread / 2 + bodyLow

bigSpreadTaken     = spread > range*0.7
averageSpreadTaken = spread > range*0.5
smallSpreadTaken   = spread < range*0.3

// projection check
f_isProjectionGettingSmaller() =>
    bool isProjectionGettingSmaller = false
    wickA = close > open ? low[3] - low[2] : high[2] - high[3]
    wickB = close > open ? low[2] - low[1] : high[1] - high[2]
    wickC = close > open ? low[1] - low    : high - high[1]
    if wickA > wickB and wickB > wickC
        isProjectionGettingSmaller := true

	_isProjectionGettingSmaller = isProjectionGettingSmaller
    [_isProjectionGettingSmaller]

f_dnLastProjectionIsBiggest() =>
    bool lastProjectionIsBiggest = false
    wickA = low[3] - low[2] 
    wickB = low[2] - low[1] 
    wickC = low[1] - low  
    if wickA < wickB and wickB < wickC
        lastProjectionIsBiggest := true

	_dnLastProjectionIsBiggest = lastProjectionIsBiggest
    [_dnLastProjectionIsBiggest]

f_upLastProjectionIsBiggest() =>
    bool lastProjectionIsBiggest = false
    wickA = high[2] - high[3] 
    wickB = high[1] - high[2] 
    wickC = high - high[1]  
    if wickA < wickB and wickB < wickC
        lastProjectionIsBiggest := true

	_upLastProjectionIsBiggest = lastProjectionIsBiggest
    [_upLastProjectionIsBiggest]

// smallest spread check
f_isSmallest(start_index, end_index) =>
    bool isSmallestSpread = true
    for i = start_index to end_index
        if spread > spread[i] 
            isSmallestSpread := false
            break

	_isSmallestSpread = isSmallestSpread
    [_isSmallestSpread]

// lowest check
f_isLowest(lowest_index, start_index, end_index) =>
    bool isLowestLow = true
    for i = start_index to end_index
        if low[lowest_index] > low[i] 
            isLowestLow := false
            break

	_isLowestLow = isLowestLow
    [_isLowestLow]
// highest check
f_isHighest(highest_index, start_index, end_index) =>
    bool isHighestHigh = true
    for i = start_index to end_index
        if high[highest_index] < high[i]
            isHighestHigh := false
            break

	_isHighestHigh = isHighestHigh
    [_isHighestHigh]

[firstPreviousBarIsHighestHigh]  = f_isHighest(1, 2, pivotlbar)
[secondPreviousBarIsHighestHigh] = f_isHighest(2, 3, pivotlbar)
[firstPreviousBarIsLowestLow]    = f_isLowest(1, 2, pivotlbar)
[secondPreviousBarIsLowestLow]   = f_isLowest(2, 3, pivotlbar)

highestBarCheck() => highestbars(high, pivotlbar) == 0 ? 1 : 0
lowestBarCheck()  => lowestbars(low, pivotlbar) == 0 ? 1 : 0
highestBarCheckWithParam(length) => highestbars(high, length) == 0 ? 1 : 0
lowestBarCheckWithParam(length)  => lowestbars(low, length) == 0 ? 1 : 0

// Marubozu
// tong chieu dau rau nen tren va rau nen duoi bang x% cua range nen
rangeTakenByBothShadows() => (upShadow + dnShadow) <= (high - low)*0.7 ? 1 : 0
// chieu dai rau nen tren so voi muc cho phep cua rau nen
spreadTakenByUpShadow()   => upShadow < pctShadow/100*spread ? 1 : 0
// chieu dai rau nen duoi so voi muc cho phep cua rau nen
spreadTakenByDnShadow()   => dnShadow < pctShadow/100*spread ? 1 : 0

marubozuUpBar = close > open and rangeTakenByBothShadows() and spreadTakenByUpShadow()
marubozuDnBar = close < open and rangeTakenByBothShadows() and spreadTakenByDnShadow()

///PinBars
[isSmallestSpread]  = f_isSmallest(1, 3)
closeInsidePreviousBar = open <= high[1] and open >= low[1] and close < high[1] and close > low[1]
bullishPinbar = spread <= spreadAvg/3 and isSmallestSpread and lowestBarCheck() and dnShadow > averageBottomWickSize*2 and upShadow*2 < dnShadow
bearishPinbar = spread <= spreadAvg/3 and isSmallestSpread and highestBarCheck() and upShadow > averageTopWickSize*2 and upShadow > dnShadow*2

//Piercing bar
bullishPiercing = blackBody[1] and longBody[1] and whiteBody and open <= low[1] and close >= bodyMiddle[1] and close < open[1]
bearishPiercing = whiteBody[1] and longBody[1] and blackBody and open >= high[1] and close <= bodyMiddle[1] and close > open[1]

// Engulfing bar
bearishEngulfing = blackBody and longBody and whiteBody[1] and mediumLongBody[1] and close <= open[1] and open >= close[1] and ( close < open[1] or open > close[1] )
bullishEngulfing = whiteBody and longBody and blackBody[1] and mediumLongBody[1] and close >= open[1] and open <= close[1] and ( close > open[1] or open < close[1] )

//Doji 
dojiBodyPercent = 5.0
shadowEqualsPercent = 100.0
shadowEquals = upShadow == dnShadow or (abs(upShadow - dnShadow) / dnShadow * 100) < shadowEqualsPercent and (abs(dnShadow - upShadow) / upShadow * 100) < shadowEqualsPercent
isDojiBody = range > 0 and spread <= range * dojiBodyPercent / 100
doji = isDojiBody and shadowEquals
dragonflyDoji = isDojiBody and upShadow <= spread
gravestoneDoji = isDojiBody and dnShadow <= spread

// Spinning Top 
spinningTopPercent = 34.0
spinningTopWhite = dnShadow >= range / 100 * spinningTopPercent and upShadow >= range / 100 * spinningTopPercent and not isDojiBody and whiteBody
spinningTopBlack = dnShadow >= range / 100 * spinningTopPercent and upShadow >= range / 100 * spinningTopPercent and not isDojiBody and blackBody

// Shooting Star / Hammer
factor = 2.0 // shows the number of times the shadow dominates the candlestick body
shadowPercent = 5.0 // size of shadows
hasUpShadow = upShadow > shadowPercent / 100 * range
hasDnShadow = dnShadow > shadowPercent / 100 * range
shootingStar = smallBody and spread > 0 and bodyHigh < hl2 and upShadow >= factor * spread and not hasDnShadow
hammer       = smallBody and spread > 0 and bodyLow > hl2 and dnShadow >= factor * spread and not hasUpShadow

// Tweezer Top/Bottom
tweezerTop  = (not isDojiBody or (hasUpShadow and hasDnShadow)) and abs(high-high[1]) <= spreadAvg*0.05 and whiteBody[1] and blackBody and longBody[1]
tweerBottom = (not isDojiBody or (hasUpShadow and hasDnShadow)) and abs(low-low[1]) <= spreadAvg*0.05 and blackBody[1] and whiteBody and longBody[1]

//=========================================================================|
//                    TWEERZER TOP/BOTTOM                                  | 
//=========================================================================|
//Tweezer Top
bool twTop_secondBar     = false
bool twTop_firstBar      = false
bool twTop_volume        = false
bool twTop_hl            = false
bool twTop_deviant       = false

if whiteBody[1] and longBody[1]
    twTop_secondBar := true

if (not isDojiBody or (hasUpShadow and hasDnShadow)) and blackBody
    twTop_firstBar := true

if abs(high-high[1]) <= spreadAvg*0.05
    twTop_deviant := true

if volume > volume[1]
    twTop_volume := true   

if firstPreviousBarIsHighestHigh or highestBarCheck() 
    twTop_hl := true

twTop() => stz and twTop_secondBar and twTop_firstBar and twTop_deviant and twTop_hl and (twTop_volume or close <= bodyMiddle[1])

//Tweezer Bottom
bool twBottom_secondBar     = false
bool twBottom_firstBar      = false
bool twBottom_volume        = false
bool twBottom_hl            = false
bool twBottom_deviant       = false

if blackBody[1] and longBody[1]
    twBottom_secondBar := true

if (not isDojiBody or (hasUpShadow and hasDnShadow)) and whiteBody
    twBottom_firstBar := true

if abs(low-low[1]) <= spreadAvg*0.05
    twBottom_deviant := true

if volume > volume[1]
    twBottom_volume := true   

if firstPreviousBarIsLowestLow or lowestBarCheck() 
    twBottom_hl := true

twBottom() => stz and twBottom_secondBar and twBottom_firstBar and twBottom_deviant and twBottom_hl and (twBottom_volume or close >= bodyMiddle[1])

//=========================================================================|
//                    ADVANCE BLOCK/ STALLED PATTERN                       | 
//=========================================================================|
//bullish
bool bullishStalled_thirdBar      = false
bool bullishStalled_secondBar     = false
bool bullishStalled_firstBar      = false

if close[2] > open[2] and marubozuUpBar[2] and spread[2] > spreadAvg and range[2] > rangeAvg
    bullishStalled_thirdBar := true

if close[1] > open[1] and close[1] > close[2] and spread[1] < spread[2] and range[1] < range[2]
    bullishStalled_secondBar := true

if close > open and close > close[1] and close > open[3]  and spread < spread[1] and range < range[1] and smallBody
    bullishStalled_firstBar := true

bullishStalled() => ssp and bullishStalled_firstBar and bullishStalled_secondBar and bullishStalled_thirdBar

// bearish
bool bearishStalled_thirdBar      = false
bool bearishStalled_secondBar     = false
bool bearishStalled_firstBar      = false

if close[2] < open[2] and marubozuDnBar[2] and spread[2] > spreadAvg and range[2] > rangeAvg
    bearishStalled_thirdBar := true

if close[1] < open[1] and close[1] < close[2] and spread[1] < spread[2] and range[1] < range[2]
    bearishStalled_secondBar := true

if close < open and close < close[1] and close < open[3] and spread < spread[1] and range < range[1] and smallBody
    bearishStalled_firstBar := true

bearishStalled() => ssp and bearishStalled_thirdBar and bearishStalled_secondBar and bearishStalled_firstBar

// Advance Block
bool bullishAD_fourthBar     = false
bool bullishAD_thirdBar      = false
bool bullishAD_secondBar     = false
bool bullishAD_firstBar      = false

if close[3] > open[3] and averageSpreadTaken[3]
    bullishAD_fourthBar := true

if close[2] > open[2] and close[2] > close[3] and (spread[2] < spread[3] or range[2] < range[3])
    bullishAD_thirdBar := true

if close[1] > open[1] and spread[1] < spread[2] and range[1] < range[2]
    bullishAD_secondBar := true

if close > low[1] and spread <= spread[1] and range <= range[1] and smallBody
    bullishAD_firstBar := true

bullishAD() => ssp and bullishAD_firstBar and bullishAD_secondBar and bullishAD_thirdBar and bullishAD_fourthBar

bool bearishAD_fourthBar     = false
bool bearishAD_thirdBar      = false
bool bearishAD_secondBar     = false
bool bearishAD_firstBar      = false

if close[3] < open[3] and averageSpreadTaken[3]
    bearishAD_fourthBar := true
    
if close[2] < open[2] and close[2] < close[3] and (spread[2] < spread[3] or range[2] < range[3])
    bearishAD_thirdBar := true

if close[1] < open[1] and spread[1] < spread[2] and range[1] < range[2]
    bearishAD_secondBar := true

if close < high[1] and spread <= spread[1] and range <= range[1] and smallBody
    bearishAD_firstBar := true

bearishAD() => ssp and bearishAD_fourthBar and bearishAD_thirdBar and bearishAD_secondBar and bearishAD_firstBar

//=========================================================================|
//                     THREE WHITE SOLDIERS                                | 
//=========================================================================|
bool threeSoldiers_firstBar    = false
bool threeSoldiers_secondBar   = false
bool threeSoldiers_thirdBar    = false

if close[2] > open[2] 
    threeSoldiers_firstBar := true

if close[1] > open[1] and close[1] > high[2] and (spread[1] >= spread[2] or range[1] >= range[2])
    threeSoldiers_secondBar := true

if close > open and close > high[1] and (spread > spread[1] or range > range[1]) and spreadTakenByUpShadow()
    threeSoldiers_thirdBar := true

threeWhiterSoldier() => s3ws and threeSoldiers_firstBar and threeSoldiers_secondBar and threeSoldiers_thirdBar 

//=========================================================================|
//                     THREE BLACK CROWS                                   | 
//=========================================================================|
bool threeCrows_firstBar    = false
bool threeCrows_secondBar   = false
bool threeCrows_thirdBar    = false

if close[2] < open[2]
    threeCrows_firstBar := true

if close[1] < open[1] and close[1] < low[2] and (spread[1] >= spread[2] or range[1] >= range[2])
    threeCrows_secondBar := true

if close < open and close < low[1] and (spread > spread[1] or range > range[1]) and spreadTakenByDnShadow()
    threeCrows_thirdBar := true

threeBlackCrows() => s3ws and threeCrows_firstBar and threeCrows_secondBar and threeCrows_thirdBar 

//=========================================================================|
//               BROADENING TRIANGLE                                       | 
//=========================================================================|
bool broTriangle_firstBar      = false
bool broTriangle_secondBar     = false

if range[1] > range[2] and high[1] > high[2] and low[1] < low[2]
    broTriangle_firstBar := true

if range > range[1] and high > high[1] and low < low[1]
    broTriangle_secondBar := true

broadeningTriangle() => sbt and broTriangle_secondBar and broTriangle_firstBar  

//=========================================================================|
//               REVERSE REJECTION/ INDECISION ZONE                        | 
//=========================================================================|
bool bearIZ_fourthBar      = false
bool bearIZ_thirdBar       = false
bool bearIZ_secondBar      = false
bool bearIZ_firstBar       = false
bool bearIZ_currentBar     = false

if close[3] < open[3] 
    bearIZ_fourthBar := true 

if close[3] < open[3] and (dnShadow[3] > averageBottomWickSize or longBody[3])
    bearIZ_thirdBar := true

if close[2] <= open[2] and close[2] <= close[3] and close[2] > low[3] and high[2] < high[3]
    bearIZ_secondBar := true

if close[1] <= close[3] and close[1] > low[3] and low[1] > low[3] and high[1] < high[3]
    bearIZ_firstBar := true

if close < close[3]
    bearIZ_currentBar := true

bearIZ() => siz and bearIZ_fourthBar and bearIZ_thirdBar and bearIZ_secondBar and bearIZ_firstBar

bool bullIZ_fourthBar      = false
bool bullIZ_thirdBar       = false
bool bullIZ_secondBar      = false
bool bullIZ_firstBar       = false
bool bullIZ_currentBar     = false

if close[3] > open[3] 
    bullIZ_fourthBar := true 

if close[3] > open[3] and (upShadow[3] > averageTopWickSize or longBody[3])
    bullIZ_thirdBar := true

if close[2] >= open[2] and close[2] >= close[3] and close[2] < high[3] and low[2] > low[3]
    bullIZ_secondBar := true

if close[1] >= open[2] and close[1] < high[3] and high[1] < high[3] and low[1] > low[3]
    bullIZ_firstBar := true

if close > open[3]
    bullIZ_currentBar := true

bullIZ() => siz and bullIZ_fourthBar and bullIZ_thirdBar and bullIZ_secondBar and bullIZ_firstBar 

//=========================================================================|
//                     SYMMETRICAL TRIANGLE                                | 
//=========================================================================|
bool symTriangle_firstBar       = false
bool symTriangle_secondBar      = false
bool symTriangle_thirdBar       = false
bool symTriangle_fourthBar      = false

if range[4] > rangeAvg or spread[4] > spreadAvg
    symTriangle_firstBar := true

if high[3] < high[4] and low[3] > low[4] 
    symTriangle_secondBar := true

if high[2] < high[3] and low[2] > low[4] and spread[2] < spreadAvg
    symTriangle_thirdBar := true

if high[1] < high[2] and low[1] > low[2] and spread[1] < spreadAvg 
    symTriangle_fourthBar := true

symmetricalTriangle() => sstr and symTriangle_firstBar and symTriangle_secondBar and symTriangle_thirdBar and symTriangle_fourthBar

bool symTriangle2_firstBar       = false
bool symTriangle2_secondBar      = false
bool symTriangle2_thirdBar       = false

if (range[2] > rangeAvg or spread[2] > spreadAvg) and not bigBody[2]
    symTriangle2_firstBar := true

if high[1] < high[2] and low[1] > low[2] 
    symTriangle2_secondBar := true

if high < high[1] and low > low[1] and close < high[1] and close > low[1] and spread < spreadAvg
    symTriangle2_thirdBar := true

symmetricalTriangle2() => sstr and symTriangle2_firstBar and symTriangle2_secondBar and symTriangle2_thirdBar

//=========================================================================|
//                     SYMMETRICAL TRIANGLE BREAKOUT                       | 
//=========================================================================|
bool symBreakout_firstBar      = false
bool symBreakout_secondBar     = false
bool symBreakout_thirdBar      = false
bool symBreakout_fourthBar     = false
bool symBreakout_breakoutBar   = false

if spread[4] > spreadAvg and range[4] > rangeAvg
    symBreakout_firstBar := true

if high[3] < high[4] and low[3] > low[4] and spread[3] < spreadAvg
    symBreakout_secondBar := true

if high[2] < high[4] and low[2] > low[4] and spread[2] < spreadAvg
    symBreakout_thirdBar := true

if high[1] < high[2] and low[1] > low[2] and spread[1] < spreadAvg
    symBreakout_fourthBar := true

f_triangleBreakout(indexBreakout) =>
	_isUp               = close > open 
	_breakDirection     = _isUp ? close > close[indexBreakout] and close > open[indexBreakout] : close < close[indexBreakout] and close < open[indexBreakout]
    [_breakDirection]

[breakDirection]  = f_triangleBreakout(4)

if averageSpreadTaken and breakDirection
    symBreakout_breakoutBar := true 

symTriangleBreakout1() => sstr and symBreakout_firstBar and symBreakout_secondBar and symBreakout_thirdBar and symBreakout_fourthBar and symBreakout_breakoutBar

bool symBreakout2_firstBar      = false
bool symBreakout2_secondBar     = false
bool symBreakout2_breakoutBar   = false

if high[2] < high[3] and low[2] > low[3] and (spread[3] < spreadAvg or range[3] > rangeAvg)
    symBreakout2_secondBar := true

if high[1] <= high[2] and low[1] >= low[2]
    symBreakout2_firstBar := true

[breakDirection2]  = f_triangleBreakout(3)

if averageSpreadTaken and breakDirection2
    symBreakout2_breakoutBar := true 

symTriangleBreakout2() => sstr and symBreakout2_firstBar and symBreakout2_secondBar and symBreakout2_breakoutBar

//=========================================================================|
//                     RASING/FAILLING THREE                               | 
//=========================================================================|
bool rising3_firstBar  = false
bool rising3_secondBar = false
bool rising3_thirdBar  = false
bool rising3_fourthBar = false
bool rising3_fifthBar  = false

if close[4] > open[4]
    rising3_firstBar := averageSpreadTaken[4] 

if close[3] <= close[4] and close[3] >= open[4] and open[3] <= close[4] and high[3] < high[4] and low[3] > low[4]
    rising3_secondBar := true

if close[2]>=open[4] and open[2] <= close[4] and close[2]<=close[4] 
    rising3_thirdBar := true

if close[1]>=open[4] and open[1] <= close[4] and close[1]<=close[4] 
    rising3_fourthBar := true

if close > close[4] and upShadow < 2*averageTopWickSize and (mediumLongBody or bigSpreadTaken)
    rising3_fifthBar := true

risingThree() => srft and rising3_firstBar and rising3_secondBar and rising3_thirdBar and rising3_fourthBar and rising3_fifthBar 

bool failling3_firstBar    = false
bool failling3_secondBar   = false
bool failling3_thirdBar    = false
bool failling3_fourthBar   = false
bool failling3_fifthBar    = false

if close[4] < open[4]
    failling3_firstBar := averageSpreadTaken[4]

if  close[3] >= close[4] and close[3] <= open[4] and open[3] >= close[4] and high[3] < high[4] and low[3] > low[4]
    failling3_secondBar := true

if close[2] >= close[4] and close[2] <= open[4] and open[2] >= close[4] 
    failling3_thirdBar := true

if close[1] >= close[4] and close[1] <= open[4] and open[1] >= close[4] 
    failling3_fourthBar := true

if close < close[4] and dnShadow < 2*averageBottomWickSize and (mediumLongBody or bigSpreadTaken)
    failling3_fifthBar :=  true

faillingThree() => srft and failling3_firstBar and failling3_secondBar and failling3_thirdBar and failling3_fourthBar and failling3_fifthBar

//=========================================================================|
//                     RASING/FAILLING THREE FALSE BREAK                   | 
//=========================================================================|
//Rising three false break| Mother maru green - green/red - green/red - green/red - Maru green - Piercing down
bool rising3fb_firstBar    = false
bool rising3fb_secondBar   = false
bool rising3fb_thirdBar    = false
bool rising3fb_fourthBar   = false
bool rising3fb_fifthBar    = false
bool rising3fb_reverseBar  = false

if close[5] > open[5]
    rising3fb_firstBar := averageSpreadTaken[5] 

if close[4] <= close[5] and close[4] >= open[5] and open[4] <= close[5] and high[4] < high[5] and low[4] > low[5]
    rising3fb_secondBar := true
    
if close[3]>=open[5] and open[3] <= close[5] and close[3]<=close[5] and high[3] < high[5] and low[3] > low[5]
    rising3fb_thirdBar := true

if close[2]>=open[5] and open[2] <= close[5] and close[2]<=close[5] and high[2] < high[5] and low[2] > low[5]
    rising3fb_fourthBar := true

if close[1] >= close[5] 
    rising3fb_fifthBar := true

if bearishPiercing or bearishEngulfing or bearishPinbar
    rising3fb_reverseBar := true

risingThreeFalseBreak() => srft and rising3fb_firstBar and rising3fb_secondBar and rising3fb_thirdBar and rising3fb_fourthBar and rising3fb_fifthBar and rising3fb_reverseBar

// Failling three false break| Mother maru red - green/red - green/red - green/red - Maru red - Piercing up
bool failling3fb_firstBar     = false
bool failling3fb_secondBar    = false
bool failling3fb_thirdBar     = false
bool failling3fb_fourthBar    = false
bool failling3fb_fifthBar     = false
bool failling3fb_reverseBar   = false

if close[5] < open[5]
    failling3fb_firstBar := averageSpreadTaken[5]

if  close[4] >= close[5] and close[4] <= open[5] and open[4] >= close[5] and high[4] < high[5] and low[4] > low[5]
    failling3fb_secondBar := true

if close[3] >= close[5] and close[3] <= open[5] and open[3] >= close[5] and high[3] < high[5] and low[3] > low[5]
    failling3fb_thirdBar := true

if close[2] >= close[5] and close[2] <= open[5] and open[2] >= close[5] and high[2] < high[5] and low[2] > low[5]
    failling3fb_fourthBar := true

if close[1] <= close[5]
    failling3fb_fifthBar :=  true

if  bullishPiercing or bullishEngulfing or bullishPinbar
    failling3fb_reverseBar := true

faillingThreeFalseBreak() => srft and failling3fb_firstBar and failling3fb_secondBar and failling3fb_thirdBar and failling3fb_fourthBar and failling3fb_fifthBar and failling3fb_reverseBar

//=========================================================================|
//                     RASING/FAILLING THREE FAIL                          | 
//=========================================================================|
// Rising three
bool rising3f_firstBar  = false
bool rising3f_secondBar = false
bool rising3f_thirdBar  = false
bool rising3f_fourthBar = false
bool rising3f_breakBar  = false

if close[4] > open[4] and averageSpreadTaken[4]
    rising3f_fourthBar := true

if close[3] <= close[4] and close[3] >= open[4] and open[3] < high[4] and high[3] < high[4]
    rising3f_thirdBar := (high[3] - low[3]) >= (abs(close[4] - open[4])*bodyPercentage)

if close[2]>=open[4] and open[2] <= close[4] and close[2]<=close[4] and high[2] < high[4] 
    rising3f_secondBar := true

if close[1]>=open[4] and open[1] <= close[4] and close[1]<=close[4] and high[1] < high[4]
    rising3f_firstBar := true

if close < open[4] and marubozuDnBar
    rising3f_breakBar := true

risingThreeFail() => srft and rising3f_firstBar and rising3f_secondBar and rising3f_thirdBar and rising3f_fourthBar and rising3f_breakBar

// falling three 
bool falling3f_firstBar  = false
bool falling3f_secondBar = false
bool falling3f_thirdBar  = false
bool falling3f_fourthBar = false
bool falling3f_breakBar  = false

if close[4] < open[4] and averageSpreadTaken[4]
    falling3f_fourthBar := true

if close[3] >= close[4] and close[3] <= open[4] and open[3] > low[4] and low[3] > low[4]
    falling3f_thirdBar := (high[3] - low[3]) >= (abs(close[4] - open[4])*bodyPercentage)

if close[2]<=open[4] and open[2] >= close[4] and close[2]>=close[4] and low[2] > low[4] 
    falling3f_secondBar := true

if close[1]<=open[4] and open[1] >= close[4] and close[1]>=close[4] and low[1] > low[4]
    falling3f_firstBar := true

if close > open[4] and marubozuUpBar
    falling3f_breakBar := true

fallingThreeFail() => srft and falling3f_firstBar and falling3f_secondBar and falling3f_thirdBar and falling3f_fourthBar and falling3f_breakBar

//=========================================================================|
//                     COILING INSIDE BARS BREAK OUT                       | 
//=========================================================================|
// green - red - green 
thirdGRG()   => close[3] > open[3] ? 1 : 0
secondGRG()  => close[2] < open[2] and open[2] <= close[3] and close[2] >= open[3] ? 1 : 0
firstGRG()   => close[1] > open[1] and open[1] >= close[2] and close[1] <= open[2] ? 1 : 0

//green - red - red
thirdGRR()   => close[3] > open[3] ? 1 : 0
secondGRR()  => close[2] < open[2] and open[2] <= close[3] and close[2] >= open[3] ? 1 : 0
firstGRR()   => close[1] < open[1] and close[1] >= close[2] ? 1 : 0

//green - green - red
thirdGGR()   => close[3] > open[3] ? 1 : 0
secondGGR()  => close[2] > open[2] and close[2] <= close[3] and open[2] >= open[3] ? 1 : 0
firstGGR()   => close[1] < open[1] and close[1] >= open[1] and open[1] <= close[2]? 1 : 0

// red - green - red 
thirdRGR()   => close[3] < open[3] ? 1 : 0
secondRGR()  => close[2] > open[2] and open[2] >= close[3] and close[2] <= open[3] ? 1 : 0
firstRGR()   => close[1] < open[1] and open[1] <= close[2] and close[1] >= open[2] ? 1 : 0

// red - green - green
thirdRGG()   => close[3] < open[3] ? 1 : 0
secondRGG()  => close[2] > open[2] and open[2] >= close[3] and close[2] <= open[3] ? 1 : 0
firstRGG()   => close[1] > open[1] and close[1] <= close[2] ? 1 : 0

// red - red - green
thirdRRG()   => close[3] < open[3] ? 1 : 0
secondRRG()  => close[2] < open[2] and close[2] >= close[3] and open[2] <= open[3] ? 1 : 0
firstRRG()   => close[1] > open[1] and close[1] <= open[2] ? 1 : 0

grg  = sib and thirdGRG() and secondGRG() and firstGRG() 
grr  = sib and thirdGRR() and secondGRR() and firstGRR() 
ggr  = sib and thirdGGR() and secondGGR() and firstGGR() 
rgr  = sib and thirdRGR() and secondRGR() and firstRGR() 
rgg  = sib and thirdRGG() and secondRGG() and firstRGG() 
rrg  = sib and thirdRRG() and secondRRG() and firstRRG() 

//=========================================================================|
//                     FAKEY                                               | 
//=========================================================================|
// fakey shooting star
fakeyUpShadow = spread < spreadAvg and (upShadow >= spread*3 or upShadow >= wm*averageTopWickSize) and highestBarCheck() and upShadow > dnShadow*2
fakeyDnShadow = spread < spreadAvg and (dnShadow >= spread*3 or dnShadow >= wm*averageBottomWickSize) and lowestBarCheck() and upShadow*2 < dnShadow 

// green - red - shooting star
fakeyUp1_secondGreenBar()       => close[2] > open[2] ? 1 : 0
fakeyUp1_firstRedBar()          => close[1] <= open[1] and open[1] <= close[2] and close[1] >= open[2] ? 1 : 0 
fakeyUp1_shootingStarBar()      => close <= high[1] and close >= low[1] and fakeyUpShadow ? 1 : 0

fakey_up1 = sfk and fakeyUp1_secondGreenBar() and fakeyUp1_firstRedBar() and fakeyUp1_shootingStarBar() 

// green - green - shooting star
fakeyUp2_secondGreenBar()       => close[2] > open[2] and close[1] <= open[2] ? 1 : 0
fakeyU2_firstGreenBar()         => close[1] >= open[1] and close <= close[2] ? 1 : 0 
fakeyUp2_shootingStarBar()      => close <= high[1] and close >= low[1] and fakeyUpShadow ? 1 : 0
fakey_up2 = sfk and fakeyUp2_secondGreenBar() and fakeyU2_firstGreenBar() and fakeyUp2_shootingStarBar()

// red - green - shooting star
fakeyUp3_secondRedBar()    => close[2] < open[2] ? 1 : 0
fakeyUp3_firstGreenBar()   => close[1] >= open[1] and open[1] >= close[2] and close[1] <= open[2] ? 1 : 0
fakeyUp3_shootingStarBar() => close <= high[1] and close >= low[1] and fakeyUpShadow ? 1 : 0
//and close <= close[1] and close >= open[1]
fakey_up3 = sfk and fakeyUp3_secondRedBar() and fakeyUp3_firstGreenBar() and fakeyUp3_shootingStarBar()

// fakey hammer
// red - green - hammer
fakeyDown1_secondRedBar()  => close[2] < open[2] ? 1 : 0
fakeyDown1_firstGreenBar() => close[1] >= open[1] and close >= open[1] and open[1] >= close[2] and close[1] <= open[2] ? 1 : 0
fakeyDown1_hammerBar()     => close >= low[1] and close <= high[1] and fakeyDnShadow ? 1 : 0
fakey_down1 = sfk and fakeyDown1_secondRedBar() and fakeyDown1_firstGreenBar() and fakeyDown1_hammerBar() 

// green - red - hammer
fakeyDown2_secondGreenBar()  => close[2] > open[2] ? 1 : 0
fakeyDown2_firstRedBar()     => close[1] <= open[1] and open[1] <= close[2] and close[1] >= open[2] ? 1 : 0
fakeyDown2_hammerBar()       => close >= low[1] and close <= high[1] and fakeyDnShadow ? 1 : 0
fakey_down2 = sfk and fakeyDown2_secondGreenBar() and fakeyDown2_firstRedBar() and fakeyDown2_hammerBar()  

// red - red - hammer
fakeyDown3_secondRedBar() => close[2] < open[2] ? 1 : 0
fakeyDown3_firstRedBar()  => close[1] <= open[1] and open[1] >= close[2] and close[1] >= close[2] ? 1 : 0
fakeyDown3_hammerBar()    => close >= low[1] and close <= high[1] and fakeyDnShadow ? 1 : 0
fakey_down3 = sfk and fakeyDown3_secondRedBar() and fakeyDown3_firstRedBar() and fakeyDown3_hammerBar()

//=========================================================================|
//                     KANGAROO TAIL                                       | 
//=========================================================================|
// range > average range
// no space on the left
// not place right after marubozu bar
// close inside the range of previous bar
// shadow >= body*3
// close at 1/3 of the top or bottom
bool topKgr_wickVolatility          = false
bool topKgr_minimumWickLength       = false
bool topKgr_noSpaceOnTheLeft        = false
bool topKgr_closeNearBottom         = false
bool topKgr_closeInsidePreviousBar  = false
bool topKgr_biggerRangePreviousBar  = false

if range - range[1] >= 0
    topKgr_biggerRangePreviousBar := true

if upShadow >= spread * 3 
    topKgr_minimumWickLength := true

if close <= low + (high - low)/3 and open <= low + (high - low)/3
    topKgr_closeNearBottom := true

if spread > 0 and open <= high[1] and open >= low[1] and close < high[1] and close > low[1]
    topKgr_closeInsidePreviousBar := true

if upShadow >= 2 * averageTopWickSize and range > range[1]
    topKgr_wickVolatility := true

if highestBarCheck()
    topKgr_noSpaceOnTheLeft := true

topKangaroo() => skgr and topKgr_minimumWickLength and topKgr_closeNearBottom and topKgr_closeInsidePreviousBar and topKgr_biggerRangePreviousBar and topKgr_wickVolatility and topKgr_noSpaceOnTheLeft

bool bottomKgr_wickVolatility          = false
bool bottomKgr_minimumWickLength       = false
bool bottomKgr_noSpaceOnTheLeft        = false
bool bottomKgr_closeNearTop            = false
bool bottomKgr_closeInsidePreviousBar  = false
bool bottomKgr_biggerRangePreviousBar  = false

if range - range[1] >= 0
    bottomKgr_biggerRangePreviousBar := true

if dnShadow >= spread * 3
    bottomKgr_minimumWickLength := true

if close >= high - (high - low) / 3 and open >= high - (high - low) / 3 
    bottomKgr_closeNearTop := true

if spread > 0 and open <= high[1] and open >= low[1] and close < high[1] and close > low[1]
    bottomKgr_closeInsidePreviousBar := true

if dnShadow >= 2 * averageBottomWickSize and range > range[1]
    bottomKgr_wickVolatility := true

if lowestBarCheck()
    bottomKgr_noSpaceOnTheLeft := true

bottomKangaroo() => skgr and bottomKgr_biggerRangePreviousBar and bottomKgr_minimumWickLength and bottomKgr_closeNearTop and bottomKgr_closeInsidePreviousBar and bottomKgr_wickVolatility and bottomKgr_noSpaceOnTheLeft

//=========================================================================|
//                     ENGULFING                                           | 
//=========================================================================|
// white
bool whiteEng_fourth      = false
bool whiteEng_third       = false
bool whiteEng_second      = false
bool whiteEng_first       = false
bool whiteEng_engulfing   = false
bool whiteEng_lowest     = false
bool whiteEng_engulfing2  = false

if close[4] < open[4]
    whiteEng_fourth := true

if close[3] < open[3]
    whiteEng_third := true

if close[2] < open[2]
    whiteEng_second := true

if close[1] < open[1]
    whiteEng_first := true

if close > open[1] and spreadTakenByUpShadow() and (low > low[1] or low > low[2]) 
    whiteEng_engulfing := true

if firstPreviousBarIsLowestLow or secondPreviousBarIsLowestLow
    whiteEng_lowest := true

whiteEngulfing()  => senf and whiteEng_fourth and whiteEng_third and whiteEng_second and whiteEng_first and whiteEng_engulfing and whiteEng_lowest

if close > open[1] and spreadTakenByUpShadow() and dnShadow > averageBottomWickSize and low < low[1]
    whiteEng_engulfing2 := true

whiteEngulfing2() => senf and whiteEng_third and whiteEng_second and whiteEng_first and whiteEng_engulfing2 and lowestBarCheck()

// black
bool blackEng_fourth      = false
bool blackEng_third       = false
bool blackEng_second      = false
bool blackEng_first       = false
bool blackEng_engulfing   = false
bool blackEng_highest     = false
bool blackEng_engulfing2  = false

if close[4] > open[4]
    blackEng_fourth := true

if close[3] > open[3]
    blackEng_third := true

if close[2] > open[2]
    blackEng_second := true

if close[1] > open[1]
    blackEng_first := true

if close < open[1] and spreadTakenByDnShadow() and (high < high[1] or high < high[2])
    blackEng_engulfing := true

if firstPreviousBarIsHighestHigh or secondPreviousBarIsHighestHigh
    blackEng_highest := true

blackEngulfing() => senf and blackEng_fourth and blackEng_third and blackEng_second and blackEng_first and blackEng_engulfing and blackEng_highest

if close < open[1] and spreadTakenByDnShadow() and upShadow > averageTopWickSize and high > high[1]
    blackEng_engulfing2 := true

blackEngulfing2() => senf and blackEng_third and blackEng_second and blackEng_first and blackEng_engulfing2 and highestBarCheck()

//=========================================================================|
//                     MORNING/EVENING STAR                                | 
//=========================================================================|
//morning
bool morning_firstBar                = false
bool morning_secondBar               = false
bool morning_thirdBar                = false

if close[2] < open[2] and averageSpreadTaken[2] and marubozuDnBar[2] and longBody
    morning_firstBar := true

if doji[1] or (hammer[1] and firstPreviousBarIsLowestLow) or bullishPinbar[1]
    morning_secondBar := true

if close > open and close > (open[2] + close[2])/2 and close > high[1] and marubozuUpBar
    morning_thirdBar := true

morningStar() => sms and morning_firstBar and morning_secondBar and morning_thirdBar

bool morning2_firstBar               = false
bool morning2_secondBar              = false
bool morning2_thirdBar               = false

if close[2] < open[2] and averageSpreadTaken[2] and spread[2] > spreadAvg and secondPreviousBarIsLowestLow
    morning2_firstBar := true

if doji[1] or hammer[1] or spinningTopWhite[1] or spinningTopBlack[1] or dragonflyDoji[1]
    morning2_secondBar := true

if close > open and close > open[2] and marubozuUpBar
    morning2_thirdBar := true

morningStar2() => sms and morning2_firstBar and morning2_secondBar and morning2_thirdBar

// evening
bool evening_firstBar               = false
bool evening_secondBar              = false
bool evening_thirdBar               = false

if close[2] > open[2] and averageSpreadTaken[2] and marubozuUpBar[2] and longBody
    evening_firstBar := true

if doji[1] or (shootingStar[1] and firstPreviousBarIsHighestHigh) or bearishPinbar[1]
    evening_secondBar := true

if close < open and close < (open[2] + close[2])/2 and close < low[1] and marubozuDnBar
    evening_thirdBar := true

eveningStar() => sms and evening_firstBar and evening_secondBar and evening_thirdBar

bool evening2_firstBar               = false
bool evening2_secondBar              = false
bool evening2_thirdBar               = false

if close[2] < open[2] and averageSpreadTaken[2]  and spread[2] > spreadAvg and secondPreviousBarIsHighestHigh
    evening2_firstBar := true

if doji[1] or shootingStar[1] or spinningTopWhite[1] or spinningTopBlack[1] or gravestoneDoji[1]
    evening2_secondBar := true

if close > open and close < close[2] and marubozuDnBar
    evening2_thirdBar := true

eveningStar2() => sms and evening2_firstBar and evening2_secondBar and evening2_thirdBar

//=========================================================================|
//                     THREE BAR REVERSAL                                  | 
//=========================================================================|
// middle bar can't be outsidebar
//  great combination of a head and shoulders formation and a three bar reversal pattern.

bool upT3R_first                = false
bool upT3R_second               = false
bool upT3R_third                = false

if close[2] < open[2]
    upT3R_third := true

if close[1] < high[2] and low[1] < low[2] and low[1] < low and firstPreviousBarIsLowestLow 
    upT3R_second := true

if close > high[1] and close >= high[2]
    upT3R_first := true

up3Reversal() => s3br and upT3R_first and upT3R_second and upT3R_third

bool dnT3R_first                = false
bool dnT3R_second               = false
bool dnT3R_third                = false

if close[2] > open[2]
    dnT3R_third := true

if close[1] > low[2] and high[1] > high[2] and high[1] > high and firstPreviousBarIsHighestHigh
    dnT3R_second := true

if close < low[1] and close <= low[2]
    dnT3R_first := true

dn3Reversal() => s3br and dnT3R_first and dnT3R_second and dnT3R_third

//=========================================================================|
//                   DECELERATION                                          | 
//=========================================================================|
bool dnDec_firstBar     = false
bool dnDec_secondBar    = false
bool dnDec_thirdBar     = false
bool dnDec_fourthBar    = false
[isProjectionGettingSmaller] = f_isProjectionGettingSmaller()

if close[3] < open[3] 
    dnDec_fourthBar := true 

if close[2] < open[2] and low[2] < low[3]
    dnDec_thirdBar := true 

if close[1] < open[1] and low[1] < low[2]
    dnDec_secondBar := true 

if close > open and low < low[1]
    dnDec_firstBar := true 

dnDeceleration() => std and dnDec_fourthBar and dnDec_thirdBar and dnDec_secondBar and dnDec_firstBar and isProjectionGettingSmaller

bool upDec_firstBar     = false
bool upDec_secondBar    = false
bool upDec_thirdBar     = false
bool upDec_fourthBar    = false

if close[3] > open[3] 
    upDec_fourthBar := true 

if close[2] > open[2] and high[2] > high[3]
    upDec_thirdBar := true 

if close[1] > open[1] and high[1] > high[2]
    upDec_secondBar := true 

if close < open and high > high[1]
    upDec_firstBar := true 

upDeceleration() => std and upDec_fourthBar and upDec_thirdBar and upDec_secondBar and upDec_firstBar and isProjectionGettingSmaller

//=========================================================================|
//                   ANTI-CLIMAX                                           | 
//=========================================================================|
bool upAC_firstBar     = false
bool upAC_secondBar    = false
bool upAC_thirdBar     = false
bool upAC_fourthBar    = false
[upLastProjectionIsBiggest] = f_upLastProjectionIsBiggest()

if close[3] > open[3] 
    upAC_fourthBar := true 

if close[2] > open[2] and high[2] > high[3]
    upAC_thirdBar := true 

if close[1] > open[1] and high[1] > high[2]
    upAC_secondBar := true 

if high > high[1]
    upAC_firstBar := true 

upAntiClimax() => sac and upAC_fourthBar and upAC_thirdBar and upAC_secondBar and upAC_firstBar and upLastProjectionIsBiggest

bool dnAC_firstBar     = false
bool dnAC_secondBar    = false
bool dnAC_thirdBar     = false
bool dnAC_fourthBar    = false
[dnLastProjectionIsBiggest] = f_dnLastProjectionIsBiggest()

if close[3] < open[3] 
    dnAC_fourthBar := true 

if close[2] < open[2] and low[2] < low[3]
    dnAC_thirdBar := true 

if close[1] < open[1] and low[1] < low[2]
    dnAC_secondBar := true 

if low < low[1]
    dnAC_firstBar := true 

dnAntiClimax() => sac and dnAC_fourthBar and dnAC_thirdBar and dnAC_secondBar and dnAC_firstBar and dnLastProjectionIsBiggest

//=========================================================================|
//                     PRESSURE INCREASE                                   | 
//=========================================================================|
// down shadow's getting longger
bool buyingPI_firstBar        = false
bool buyingPI_secondBar       = false
bool buyingPI_thirdBar        = false
bool buyingPI_closeAbove      = false

if close[2] < open[2] and dnShadow[2] > dnShadow[3] and low[2] < low[3]
    buyingPI_thirdBar := true 
 
if dnShadow[1] > dnShadow[2] and low[1] < low[2]
    buyingPI_secondBar := true 

if  dnShadow > averageBottomWickSize and dnShadow > dnShadow[1] and low < low[1]
    buyingPI_firstBar := true

if close[3] > open[3] 
    buyingPI_closeAbove := close[2] < open[3]

if close[3] < open[3] 
    buyingPI_closeAbove := close[2] < close[3]

buyingPI() => spi and buyingPI_firstBar and buyingPI_secondBar and buyingPI_thirdBar and buyingPI_closeAbove and not closeAboveEMA25

// up shadow's getting longger
bool sellingPI_firstBar        = false
bool sellingPI_secondBar       = false
bool sellingPI_thirdBar        = false
bool sellingPI_closeAbove      = false

if close[2] > open[2] and upShadow[2] > upShadow[3] and high[2] > high[3]
    sellingPI_thirdBar := true 
 
if upShadow[1] > upShadow[2] and high[1] > high[2]
    sellingPI_secondBar := true 

if upShadow > averageTopWickSize and upShadow > upShadow[1] and high > high[1]
    sellingPI_firstBar := true

if close[3] < open[3] 
    sellingPI_closeAbove := close[2] > open[3]

if close[3] > open[3] 
    sellingPI_closeAbove := close[2] > close[3]

sellingPI() => spi and sellingPI_firstBar and sellingPI_secondBar and sellingPI_thirdBar and sellingPI_closeAbove and not closeBelowEMA25

// down shadow's getting longger and up shadow's getting shorter
bool buyingPI2_firstBar        = false
bool buyingPI2_secondBar       = false
bool buyingPI2_thirdBar        = false

if close[2] < open[2]
    buyingPI2_thirdBar := true 
 
if close[1] < open[1] and dnShadow[1] > dnShadow[2] and upShadow[1] < upShadow[2]
    buyingPI2_secondBar := true 

if  dnShadow > dnShadow[1] and upShadow < upShadow[1]
    buyingPI2_firstBar := true

buyingPI2() => spi and buyingPI2_firstBar and buyingPI2_secondBar and buyingPI2_thirdBar and not closeAboveEMA25

// up shadow's getting longger and down shadow's getting shorter
bool sellingPI2_firstBar        = false
bool sellingPI2_secondBar       = false
bool sellingPI2_thirdBar        = false

if close[2] > open[2] 
    sellingPI2_thirdBar := true 
 
if close[1] > open[1] and upShadow[1] > upShadow[2] and dnShadow[1] < dnShadow[2]
    sellingPI2_secondBar := true 

if upShadow > upShadow[1] and dnShadow < dnShadow[1]
    sellingPI2_firstBar := true

sellingPI2() => spi and sellingPI2_firstBar and sellingPI2_secondBar and sellingPI2_thirdBar and not closeBelowEMA25

//=========================================================================|
//                     PRESSURE ZONE                                       | 
//=========================================================================|
//selling pressure zone
bool sellingPZ_firstBar        = false
bool sellingPZ_secondBar       = false
bool sellingPZ_thirdBar        = false
bool sellingPZ_highestBars     = false
bool sellingPZ_zone            = false
bool sellingPZ_longWick        = false
bool sellingPZ_notInsideBar    = false
bool sellingPZ_minimumPZ       = true

if upShadow[2] > dnShadow[2] and upShadow[2] > averageTopWickSize
    sellingPZ_thirdBar := true 
 
if close[1] < high[2]
    sellingPZ_secondBar := true 

if close < high[1] and close < high[2] and upShadow > averageTopWickSize
    sellingPZ_firstBar := true

if firstPreviousBarIsHighestHigh or secondPreviousBarIsHighestHigh or highestBarCheck()
    sellingPZ_highestBars := true 

if high > bodyHigh[2] and high > bodyHigh[1] and high[1] > bodyHigh[2]
    sellingPZ_zone := true

if upShadow[2] > averageTopWickSize*wm or upShadow[1] > averageTopWickSize*wm
    sellingPZ_longWick := true 
    
// specific handle middle bar can not close above 0.5 wick of first bar
if close[2] > open[2] and close[1] > open[1] and close[1] - open[1] > (high[2] - bodyHigh[2])/2
    sellingPZ_minimumPZ := false

sellingPZ() => spz and sellingPZ_firstBar and sellingPZ_secondBar and sellingPZ_thirdBar and sellingPZ_highestBars and sellingPZ_zone and sellingPZ_longWick and sellingPZ_minimumPZ

//buying pressure zone
bool buyingPZ_firstBar        = false
bool buyingPZ_secondBar       = false
bool buyingPZ_thirdBar        = false
bool buyingPZ_lowestBars      = false
bool buyingPZ_zone            = false
bool buyingPZ_longWick        = false
bool buyingPZ_minimumPZ       = true

if dnShadow[2] > upShadow[2] and dnShadow[2] > averageBottomWickSize
    buyingPZ_thirdBar := true 
 
if close[1] > low[2]
    buyingPZ_secondBar := true 

if  close > low[1] and close > low[2] and dnShadow > averageBottomWickSize
    buyingPZ_firstBar := true

if firstPreviousBarIsLowestLow or secondPreviousBarIsLowestLow or lowestBarCheck() 
    buyingPZ_lowestBars := true 

if low < bodyLow[2] and low < bodyLow[1] and low[1] < bodyLow[2]
    buyingPZ_zone := true

if dnShadow[2] > averageBottomWickSize*wm or dnShadow[1] > averageBottomWickSize*wm
    buyingPZ_longWick := true 

// specific handle middle bar can not close above 0.5 wick of first bar
if close[2] < open[2] and close[1] < open[1] and open[1] - close[1] > (bodyLow[2] - low[2])/2
    buyingPZ_minimumPZ := false

buyingPZ() => spz and buyingPZ_firstBar and buyingPZ_secondBar and buyingPZ_thirdBar and buyingPZ_lowestBars and buyingPZ_zone and buyingPZ_longWick and buyingPZ_minimumPZ

//=========================================================================|
//                     CONGESTION ZONE BREAK                               | 
//=========================================================================|
congestionZone_4pi()   => range[4] > rangeAvg or averageSpreadTaken[4] ? 1 : 0
congestionZone_3()     => close[3] <= high[4] and close[3] >= low[4]   ? 1 : 0
congestionZone_2()     => close[2] <= high[3] and close[2] >= low[3]   ? 1 : 0
congestionZone_1()     => close[1] <= high[2] and close[1] >= low[2]   ? 1 : 0
congestionZone_0br()   => close < low[1] or close > high[1]            ? 1 : 0

congZoneBreakout4  = scz and congestionZone_4pi() and congestionZone_3() and congestionZone_2() and congestionZone_1() and congestionZone_0br() 

congestionZone_4()     => close[4] <= high[5] and close[4] >= low[5]   ? 1 : 0
congestionZone_5pi()   => range[5] > rangeAvg or averageSpreadTaken[5] ? 1 : 0

congZoneBreakout6  = scz and congestionZone_5pi() and congestionZone_4() and congestionZone_3() and congestionZone_2() and congestionZone_1() and congestionZone_0br() 

//=========================================================================|
//                     STAIR STEP                                          | 
//=========================================================================|
// red - green - red - green - ?
upSS_4()     => close[4] < open[4]                                               ? 1 : 0
upSS_3()     => close[3] > open[3] and open[3] > close[4] and close[3] > open[4] ? 1 : 0
upSS_2()     => close[2] < open[2] and open[2] > close[3] and close[2] > open[3] ? 1 : 0
upSS_1()     => close[1] > open[1] and open[1] > close[2] and close[1] > open[2] ? 1 : 0
upSS_0()     => high > high[1] or open > close[1]                                ? 1 : 0

upStairStep = sss and upSS_4() and upSS_3() and upSS_2() and upSS_1() and upSS_0()

// green - red - green - red - ?
dnSS_4()     => close[4] > open[4]                                               ? 1 : 0
dnSS_3()     => close[3] < open[3] and open[3] > close[4] and close[3] > open[4] ? 1 : 0
dnSS_2()     => close[2] > open[2] and open[2] > close[3] and close[2] > open[3] ? 1 : 0
dnSS_1()     => close[1] < open[1] and open[1] > close[2] and close[1] > open[2] ? 1 : 0
dnSS_0()     => low < low[1] or open < close[1]                                  ? 1 : 0

dnStairStep = sss and dnSS_4() and dnSS_3() and dnSS_2() and dnSS_1() and dnSS_0()

// SS false break
// green - red - green - red(false break) - green(reverse)
upSSFB_4()     => close[4] > open[4]                                               ? 1 : 0
upSSFB_3()     => close[3] < open[3] and open[3] > close[4] and close[3] > open[4] ? 1 : 0
upSSFB_2()     => close[2] > open[2] and open[2] > close[3] and close[2] > open[3] ? 1 : 0
upSSFB_1()     => close[1] < open[1] and close[1] < open[2]                       ? 1 : 0
upSSFB_0()     => close > open and close > high[1]                                 ? 1 : 0

upStairStepFalseBreak = sss and upSSFB_4() and upSSFB_3() and upSSFB_2() and upSSFB_1() and upSSFB_0()

// red - green - red - green(false break) - red(reverse)
dnSSFB_4()     => close[4] < open[4]                                               ? 1 : 0
dnSSFB_3()     => close[3] > open[3] and open[3] > close[4] and close[3] > open[4] ? 1 : 0
dnSSFB_2()     => close[2] < open[2] and open[2] > close[3] and close[2] > open[3] ? 1 : 0
dnSSFB_1()     => close[1] > open[1] and close[1] > open[2]                        ? 1 : 0
dnSSFB_0()     => close < open and close < low[1]                                  ? 1 : 0

dnStairStepFalseBreak = sss and dnSSFB_4() and dnSSFB_3() and dnSSFB_2() and dnSSFB_1() and dnSSFB_0()
//------------------------------------------------------------------------------
patternLabelPosLow = low - (atr(30) * 0.6)
patternLabelPosHigh = high + (atr(30) * 0.6)
labelPosition = close > open ? patternLabelPosLow : patternLabelPosHigh
labelStyle = close > open ? label.style_label_up : label.style_label_down

// Inside bars break out
barcolor((grg or ggr or grr or rgr or rgg or rrg) and (close > high[1] or close < low[1]) ? color_breakout : na)

// Congestion zone
barcolor(congZoneBreakout4 or congZoneBreakout6 ? color_breakout : na)

// rising/failling three
barcolor(risingThree() or faillingThree() ? color_breakout : na)

// rising/failling three fail/false break
barcolor(risingThreeFail() or fallingThreeFail() or risingThreeFalseBreak() or faillingThreeFalseBreak() ? color_falsebreak : na)

//Triangle 
barcolor(symTriangleBreakout1() or symTriangleBreakout2() ? color_breakout : na)

// Engulfing
barcolor(whiteEngulfing() or whiteEngulfing2() or blackEngulfing() or blackEngulfing2() ? color_reverse : na)

// Morning/Evening Star
barcolor(morningStar() or morningStar2() or eveningStar() or eveningStar2() ? color_reverse : na)

// Kangaroo
// barcolor(topKangaroo() or bottomKangaroo() ? color_pinbar : na)

//fakey
// barcolor(fakey_up1 or fakey_up2 or fakey_up3 or fakey_down1 or fakey_down2 or fakey_down3  ? color_pinbar : na)

//Pinbar
// barcolor(spb and (bullishPinbar or bearishPinbar) and closeInsidePreviousBar and range > range[1]*0.7 ? color_pinbar : na)

// three white soldiers / three black crows
barcolor(threeBlackCrows() ? color_be_momentum : na, offset=-2)
barcolor(threeBlackCrows() ? color_be_momentum : na, offset=-1)
barcolor(threeBlackCrows() ? color_be_momentum : na)

barcolor(threeWhiterSoldier() ? color_bu_momentum : na, offset=-2)
barcolor(threeWhiterSoldier() ? color_bu_momentum : na, offset=-1)
barcolor(threeWhiterSoldier() ? color_bu_momentum : na)

//Stalled pattern 
plotshape(bullishStalled(), title="Stalled", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(bullishStalled(), title="Stalled", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)
plotshape(bullishStalled(), title="Stalled", color=color.maroon, style=shape.diamond, location=location.belowbar, size=size.tiny)

plotshape(bearishStalled(), title="Stalled", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(bearishStalled(), title="Stalled", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)
plotshape(bearishStalled(), title="Stalled", color=color.lime, style=shape.diamond, location=location.abovebar, size=size.tiny)

// Advance block
plotshape(bullishAD(), title="Advance Block", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(bullishAD(), title="Advance Block", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)
plotshape(bullishAD(), title="Advance Block", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-3)
plotshape(bullishAD(), title="Advance Block", color=color.maroon, style=shape.diamond, location=location.belowbar, size=size.tiny)
if bullishAD()
    var ttADBottom = "An advance block is a fourth-period candlestick pattern considered to forecast a reversal"
    label.new(bar_index, patternLabelPosHigh, text="AD", style=label.style_label_down, color = color.blue, textcolor=color.white, tooltip = ttADBottom)


plotshape(bearishAD(), title="Advance Block", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(bearishAD(), title="Advance Block", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)
plotshape(bearishAD(), title="Advance Block", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-3)
plotshape(bearishAD(), title="Advance Block", color=color.lime, style=shape.diamond, location=location.abovebar, size=size.tiny)
if bearishAD()
    var ttADTop = "An advance block is a fourth-period candlestick pattern considered to forecast a reversal"
    label.new(bar_index, patternLabelPosLow, text="AD", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttADTop)

// Deceleration
plotshape(upDeceleration(), title="Deceleration", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(upDeceleration(), title="Deceleration", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)
plotshape(upDeceleration(), title="Deceleration", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-3)
plotshape(upDeceleration(), title="Deceleration", color=color.maroon, style=shape.diamond, location=location.belowbar, size=size.tiny)
if upDeceleration()
    var ttDecTop = "A > B > C"
    label.new(bar_index, patternLabelPosHigh, text="DC", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttDecTop)


plotshape(dnDeceleration(), title="Deceleration", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(dnDeceleration(), title="Deceleration", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)
plotshape(dnDeceleration(), title="Deceleration", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-3)
plotshape(dnDeceleration(), title="Deceleration", color=color.lime, style=shape.diamond, location=location.abovebar, size=size.tiny)
if dnDeceleration()
    var ttDecBottom = "A < B < C"
    label.new(bar_index, patternLabelPosLow, text="DC", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttDecBottom)


// Anti Climax
plotshape(upAntiClimax(), title="Anti Climax", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(upAntiClimax(), title="Anti Climax", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)
plotshape(upAntiClimax(), title="Anti Climax", color=color.lime, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-3)
plotshape(upAntiClimax(), title="Anti Climax", color=color.maroon, style=shape.diamond, location=location.belowbar, size=size.tiny)
if upAntiClimax()
    var ttATTop = "A < B < C"
    label.new(bar_index, patternLabelPosHigh, text="AC", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttATTop)

plotshape(dnAntiClimax(), title="Anti Climax", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(dnAntiClimax(), title="Anti Climax", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)
plotshape(dnAntiClimax(), title="Anti Climax", color=color.maroon, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-3)
plotshape(dnAntiClimax(), title="Anti Climax", color=color.lime, style=shape.diamond, location=location.abovebar, size=size.tiny)
if dnAntiClimax()
    var ttATBottom = "A < B < C"
    label.new(bar_index, patternLabelPosLow, text="AC", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttATBottom)

//Pressure Zone
plotshape(buyingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny)
plotshape(buyingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(buyingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)

plotshape(sellingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny)
plotshape(sellingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(sellingPZ(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)

// Three Bar Reversal
plotshape(up3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny)
plotshape(up3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-1)
plotshape(up3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowup, location=location.belowbar, size=size.tiny, offset=-2)

plotshape(dn3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny)
plotshape(dn3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-1)
plotshape(dn3Reversal(), title="Pressure zone", color=color.navy, style=shape.arrowdown, location=location.abovebar, size=size.tiny, offset=-2)

//Hook Reversal


// Tweezer Top/Bottom
if twTop()
    var ttBearishTweezerTop = "Tweezer Top\nTweezer Top is a two-candle pattern that signifies a potential bearish reversal. The pattern is found during an uptrend. The first candle is long and green, the second candle is red, and its high is nearly identical to the high of the previous candle. The virtually identical highs, together with the inverted directions, hint that bears might be taking over the market."
    label.new(bar_index, patternLabelPosHigh, text="TT", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttBearishTweezerTop)

if twBottom()
    var ttBullishTweezerBottom = "Tweezer Bottom\nTweezer Bottom is a two-candle pattern that signifies a potential bullish reversal. The pattern is found during a downtrend. The first candle is long and red, the second candle is green, its lows nearly identical to the low of the previous candle. The virtually identical lows together with the inverted directions hint that bulls might be taking over the market."
    label.new(bar_index, patternLabelPosLow, text="TB", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttBullishTweezerBottom)

// Pressure Increase
if sellingPI()
    var ttSPI = "Selling Pressure Increase. Up Shadow's getting longer"
    label.new(bar_index, patternLabelPosHigh, text="SPI", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttSPI)

if sellingPI2()
    var ttSPI2 = "Selling Pressure Increase. Up Shadow's getting longer and Down Shadow's getting shorter"
    label.new(bar_index, patternLabelPosHigh, text="SPI", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttSPI2)

if buyingPI()
    var ttBPI = "Buying Pressure Increase. Down Shadow's getting longer"
    label.new(bar_index, patternLabelPosLow, text="BPI", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttBPI)

if buyingPI2()
    var ttBPI2 = "Buying Pressure Increase. Down Shadow's getting longer and Up Shadow's getting shorter"
    label.new(bar_index, patternLabelPosLow, text="BPI", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttBPI2)

// Kangaroo Tail
if bottomKangaroo()
    var ttBKT = "Kangaroo tails may print buy signals—bullish kangaroo tails---and bearish kangaroo tails, which are sell signals."
    label.new(bar_index, patternLabelPosLow, text="K", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttBKT)

if topKangaroo()
    var ttSKT = "Kangaroo tails may print buy signals—bullish kangaroo tails---and bearish kangaroo tails, which are sell signals."
    label.new(bar_index, patternLabelPosHigh, text="K", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttSKT)

// Inside Bar Fakey
if fakey_up1 or fakey_up2 or fakey_up3
    var ttSFK = "The Fakey pattern can be best be described as a “false-breakout from an inside bar pattern”"
    label.new(bar_index, patternLabelPosHigh, text="F", style=label.style_label_down, color = color.red, textcolor=color.white, tooltip = ttSFK)

if fakey_down1 or fakey_down2 or fakey_down3
    var ttBFK = "The Fakey pattern can be best be described as a “false-breakout from an inside bar pattern”"
    label.new(bar_index, patternLabelPosLow, text="F", style=label.style_label_up, color = color.blue, textcolor=color.white, tooltip = ttBFK)

// Neutral
// Symmetrical Triangle
if symmetricalTriangle() or symmetricalTriangle2()
    var ttST = "A symmetrical triangle is a chart pattern characterized by two converging trend lines connecting a series of sequential peaks and troughs. These trend lines should be converging at a roughly equal slope"
    label.new(bar_index, labelPosition, text="ST", style=labelStyle, color = color.gray, textcolor=color.white, tooltip = ttST)

// Broadening triangle
if broadeningTriangle() 
    var ttBT = "Broadening is characterized by increasing price volatility and diagrammed as two diverging trend lines, one rising and one falling."
    label.new(bar_index, labelPosition, text="BT", style=labelStyle, color = color.gray, textcolor=color.white, tooltip = ttBT)

// Coiling Inside Bars
if (grg or ggr or grr or rgr or rgg or rrg) and (close < high[1] and close > low[1])
    var ttCIB = "These patterns signify a prolonged period of indecision in the market and they can come before very powerful breakout moves"
    label.new(bar_index, labelPosition, text="CIB", style=labelStyle, color = color.gray, textcolor=color.white, tooltip = ttCIB)

// Doji
if sdj and (doji or dragonflyDoji or gravestoneDoji)
    var ttDoji = "Doji\nWhen the open and close of a security are essentially equal to each other, a doji candle forms. The length of both upper and lower shadows may vary, causing the candlestick you are left with to either resemble a cross, an inverted cross, or a plus sign. Doji candles show the playout of buyer-seller indecision in a tug-of-war of sorts. As price moves either above or below the opening level during the session, the close is either at or near the opening level."
    label.new(bar_index, labelPosition, text="DJ", style=labelStyle, color = color.gray, textcolor=color.white, tooltip = ttDoji)

//Stair step
if upStairStep or dnStairStep
    var ttSS = "Like the flag, the stair-step is going to occur after a sharp trend to the upside or downside"
    label.new(bar_index, labelPosition, text="SS", style=labelStyle, color = color.gray, textcolor=color.white, tooltip = ttSS)

// Break out
// Indecision Zone
if bearIZ() or bullIZ()
    var ttIZ = "The IZ pattern that come about due to indecision candlesticks can provide hints to the direction price are likely to move in the long run."
    label.new(bar_index, labelPosition, text="IZB", style=labelStyle, color = color.orange, textcolor=color.white, tooltip = ttIZ)

//Stair step
if upStairStepFalseBreak or dnStairStepFalseBreak
    var ttSSFB = "Like the flag, the stair-step is going to occur after a sharp trend to the upside or downside"
    label.new(bar_index, labelPosition, text="SSFB", style=labelStyle, color = color.orange, textcolor=color.white, tooltip = ttSSFB)
